add_subdirectory(CompMin3D_Restart )
add_subdirectory(Helmholtz3D_SurfaceLengthScale_SymmPlane)
add_subdirectory(MPCs_Helmholtz)
add_subdirectory(Thermoplasticity)
add_subdirectory(Tmech_PNorm_Opt)
add_subdirectory(Thermal_Opt)
add_subdirectory(LaminarFlowRe100)
add_subdirectory(ParallelESP)
add_subdirectory(ESP_2block)
add_subdirectory(CompMin3D_Orthotropic_ROL_LC)
add_subdirectory(Helmholtz3D_Projection_ROL_LC)
add_subdirectory(Stress_ROL_BC)
add_subdirectory(Thermomechanics)
add_subdirectory(VolAvgTensile)
add_subdirectory(NaturalConvectionGr1e3)
