# CMake generated Testfile for 
# Source directory: /fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/analyze/functional/CompMin3D_Krino_bracket
# Build directory: /ceeGPFS/fgs/bwclark/plato_move_krino_to_pe/plato/platoanalyze/spack-build-uc6pk4l/integration_tests/analyze/functional/CompMin3D_Krino_bracket
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(analyze_functional_CompMin3D_Krino_bracket "/ceeGPFS/fgs/bwclark/plato_move_krino_to_pe/plato/spack/opt/spack/linux-rhel8-x86_64/gcc-10.2.0/cmake-3.27.7-j2xc4oeifp627hntfcj5ywtyv2kwmhqy/bin/cmake" "-DTEST_COMMAND=plato input.i" "-DOUT_FILE=ROL_Optimizer.txt" "-DGOLD_FILE=ROL_Optimizer.txt.gold" "-DNUMDIFF_COMMAND=numdiff" "-DNUMDIFF_ABSOLUTE=FALSE" "-DNUMDIFF_TOLERANCE=1e-4" "-DNDSELECT_OPTIONS=" "-P" "/ceeGPFS/fgs/bwclark/plato_move_krino_to_pe/plato/platoanalyze/spack-build-uc6pk4l/integration_tests/analyze/utilities/cmake/runnumdifftest.cmake")
set_tests_properties(analyze_functional_CompMin3D_Krino_bracket PROPERTIES  _BACKTRACE_TRIPLES "/fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/utilities/cmake/tools.cmake;376;add_test;/fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/analyze/functional/CompMin3D_Krino_bracket/CMakeLists.txt;17;Plato_add_numdiff_test;/fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/analyze/functional/CompMin3D_Krino_bracket/CMakeLists.txt;0;")
add_test(analyze_functional_CompMin3D_Krino_bracket_Gradient_Check "python" "/ceeGPFS/fgs/bwclark/plato_move_krino_to_pe/plato/platoanalyze/spack-build-uc6pk4l/integration_tests/analyze/utilities/python/confirm_gradient_convergence_trend.py" "1" "1e-1" "ROL_gradient_check_output.txt" "ROL_gradient_check_output.txt.gold" "5")
set_tests_properties(analyze_functional_CompMin3D_Krino_bracket_Gradient_Check PROPERTIES  DEPENDS "analyze_functional_CompMin3D_Krino_bracket" _BACKTRACE_TRIPLES "/fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/analyze/functional/CompMin3D_Krino_bracket/CMakeLists.txt;27;add_test;/fgs/bwclark/plato_move_krino_to_pe/plato/plato-integration-tests/analyze/functional/CompMin3D_Krino_bracket/CMakeLists.txt;0;")
